name: Schedule Packages Test

on:
    workflow_dispatch:
    # Runs at 00:00 UTC on the 1, 16 and 31th of every month、
    schedule:
        - cron:  '0 0 */15 * *'


# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
    pages: write      # to deploy to Pages
    id-token: write   # to verify the deployment originates from an appropriate source

concurrency:
    group: pkgs-test
    cancel-in-progress: false # wait for finish.

jobs:
    master-stm32h750-artpi-test:
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: stm32/stm32h750-artpi:sourcery-arm
            rt-thread-versions: branch:master
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false

    master-k210-test:
        needs: master-stm32h750-artpi-test
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: k210:sourcery-riscv-none-embed
            rt-thread-versions: branch:master
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false

    master-qemu-vexpress-a9-test:
        needs: master-k210-test
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: qemu-vexpress-a9:sourcery-arm
            rt-thread-versions: branch:master
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false

    v4_1_1-stm32h750-artpi-test:
        needs: master-qemu-vexpress-a9-test
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: stm32/stm32h750-artpi:sourcery-arm
            rt-thread-versions: tag:v4.1.1
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false

    v4_1_1-k210-test:
        needs: v4_1_1-stm32h750-artpi-test
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: k210:sourcery-riscv-none-embed
            rt-thread-versions: tag:v4.1.1
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false

    v4_1_1-qemu-vexpress-a9-test:
        needs: v4_1_1-k210-test
        uses: RT-Thread/pkgs-test/.github/workflows/pkgs-action.yml@main
        with:
            bsps: qemu-vexpress-a9:sourcery-arm
            rt-thread-versions: tag:v4.1.1
            package-append-res: true
            package-test-all: true
            deploy-pages: true
            check-errors: false
